### ISSUE TITLE
不能正常使用，没有输出图片

### ISSUE THREAD

**Issue by GengGode** [xingchuanzhen/RePKG-WPF#2]
![image](https://user-images.githubusercontent.com/47711102/174969215-5ba1ae54-e3ed-41c2-bba1-875baa9f0707.png)

**Comment by Xing-Fax** [comment]
能否将被执行文件发送给我测试呢？

**Comment by GengGode** [comment]
[scene (2).zip](https://github.com/xingchuanzhen/RePKG-WPF/files/8965230/scene.2.zip)
这是其中一个，我不知道是缺少运行环境还是什么，是需要repkg.exe在目录下吗？

**Comment by Xing-Fax** [comment]
经过我的调试，发现是文件名称中含有“(”和“)”符号导致，请尝试移除掉它，然后重试
此问题会在下一个版本中修复，谢谢

**Comment by GengGode** [comment]
哦，是的移除之后就可以了，感谢 ヾ(≧▽≦*)o
